version: 2.1

orbs:
  hello: circleci/hello-build@0.0.5
  orb-tools: circleci/orb-tools@2.0.2
  slack: circleci/slack@1.0.0
  gcp-cli: circleci/gcp-cli@1.0.4

workflows:
  "Hello Workflow":
    jobs:
      - hello/hello-build

      - slack/approval-notification:
          message: Pending approval
          requires:
            - hello/hello-build

  test_orb:
    jobs:
      - orb-tools/test-in-builds:
          orb-location: src/hello-world/orb.yml
          orb-name: hello-world
          test-steps:
            - orb-tools/local-test-build:
                test-config-location: src/hello-world/test.yml

  install_and_configure_cli:
    executor: default
    jobs:
      - gcp-cli/install_and_initialize_cli:
          context: myContext
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE
